[package]
name = "Vuni"
version = "0.1.0"
authors = ["Jonas Galvez <jonasgalvez@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-js = "0.3.3"

